# 
# gp-swift-storage-kit
# Copyright (c) 2023, Greg PFISTER. MIT License
#

name: Build

on:
  release:
    types: [ 'published' ]
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    # - name: Run tests
    #  run: swift test -v
